In [ ]:
"""
Taylor Richardson
September 28, 2018.

In this analysis I try to determine if I could predict body fat with a linear regression model.

The results had a 71% R2 score, so it wasn't bad. Based on our RMSE of 2.6, being greater than 10% of our dependant variable's mean of 2.02, which means our model has high error variance. 

This means that our model is relatively accurate and could be used for predictive analysis but isn’t accurate enough to make dependable forecasts. 
"""

In [38]:
#Import all of your libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [39]:
#Load in the ‘bodyfatanalysis’ dataset
dataset = pd.read_csv('./bodyfatanalysis.csv')
dataset.head()

Triceps  Thigh  Midarm  Bodyfat
0     19.5   43.1    29.1     11.9
1     24.7   49.8    28.2     22.8
2     30.7   51.9    37.0     18.7
3     29.8   54.3    31.1     20.1
4     19.1   42.2    30.9     12.9

In [40]:
#Show the key statistics of the dataset to understand the variables and see how it is distributed
dataset.describe()

Triceps      Thigh     Midarm    Bodyfat
count  20.000000  20.000000  20.000000  20.000000
mean   25.305000  51.170000  27.620000  20.195000
std     5.023259   5.234612   3.647147   5.106186
min    14.600000  42.200000  21.300000  11.700000
25%    21.500000  47.775000  24.750000  17.050000
50%    25.550000  52.000000  27.900000  21.200000
75%    29.900000  54.625000  30.025000  24.275000
max    31.400000  58.600000  37.000000  27.200000

In [41]:
#Declare which of the variables within the dataset are the dependent(y) and independent variables (x)
#In this case our body fat is the dependent and will be the y, and the rest of the columns will be the x independent values
x = dataset.iloc[:,0:3].values
y = dataset.iloc[:,3].values

In [42]:
#Confirm that you have copied the correct data into each variable
x

array([[19.5, 43.1, 29.1],
       [24.7, 49.8, 28.2],
       [30.7, 51.9, 37. ],
       [29.8, 54.3, 31.1],
       [19.1, 42.2, 30.9],
       [25.6, 53.9, 23.7],
       [31.4, 58.5, 27.6],
       [27.9, 52.1, 30.6],
       [22.1, 49.9, 23.2],
       [25.5, 53.5, 24.8],
       [31.1, 56.6, 30. ],
       [30.4, 56.7, 28.3],
       [18.7, 46.5, 23. ],
       [19.7, 44.2, 28.6],
       [14.6, 42.7, 21.3],
       [29.5, 54.4, 30.1],
       [27.7, 55.3, 25.7],
       [30.2, 58.6, 24.6],
       [22.7, 48.2, 27.1],
       [25.2, 51. , 27.5]])

In [43]:
#And for y
y

array([11.9, 22.8, 18.7, 20.1, 12.9, 21.7, 27.1, 25.4, 21.3, 19.3, 25.4,
       27.2, 11.7, 17.8, 12.8, 23.9, 22.6, 25.4, 14.8, 21.1])

In [44]:
#Load into the function to split the data from sklearn
from sklearn.model_selection import train_test_split
#You want to split up the data into both training and testing sets, using 80% for training and 20% for testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=100)

In [45]:
#We will train the algorithm using linear regression
#First importing the function from sklearn
from sklearn.linear_model import LinearRegression
#Name the LinearRegression function regressor
regressor = LinearRegression()
#Use the function on our training data and display the output
regressor.fit(x_train, y_train)
regressor.coef_

array([ 5.94241317, -4.25379312, -3.06543785])

In [46]:
#You also need to find the intercept
regressor.intercept_

172.33769259504064

In [47]:
#Use the data from x_test to predict y values later.
y_pred = regressor.predict(x_test)

In [48]:
#Check if the data is in a 2d or 1d array
y_pred

array([27.11652216, 20.84351425, 25.04509166, 19.12427721])

In [50]:
#We need to transpose our data into a 1D array
ytest1 = y_test.reshape(-1)
ypred1 = y_pred.reshape(-1)

In [51]:
#Create a forecast table that tests your model by running the model on your x test data to determine what y data your model says you will receive, and compare it to the real y data.
FcstTble = pd.DataFrame({'Actual':ytest1,'Predicted':ypred1})
FcstTble

Actual  Predicted
0    25.4  27.116522
1    21.1  20.843514
2    27.2  25.045092
3    14.8  19.124277

In [52]:
#Accuracy Score using R2
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.7109775284996336

In [53]:
#MAE, MSE, and RMSE tests
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 2.113048363774462
Mean Squared Error: 6.588809154984915
Root Mean Squared Error: 2.56686757644116
